[functions]
  # Dis à Netlify où sont tes Functions
  directory = "netlify/functions"
  node_bundler = "esbuild"

# (Optionnel mais pratique) URLs jolies :
# /api/xxx -> /.netlify/functions/xxx
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
