[build]
  command = "echo 'no build'"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  [functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/blobs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
