[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/spaces"
  to   = "/.netlify/functions/spaces"
  status = 200

[[redirects]]
  from = "/api/spaces/batch"
  to   = "/.netlify/functions/spaces"
  status = 200
